import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import {AuthProvider} from "@/contexts/AuthContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <AuthProvider>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <nav>
        <Link href="/">Home</Link>
        <Link href="/signup">Sign Up</Link>
        <Link href="/login">Login</Link>
        <Link href="/confirm">Confirm Account</Link>
      </nav>
        {children}
      </body>
    </AuthProvider>
    </html>
  );
}
